[presets.abwasser]
dir = "covid/abwassermonitoring"
default_file_extension = ".json"

[presets.wienabwasser]
dir = "covid/abwassermonitoring/wien"
default_file_extension = ".csv"

# covid/

  [[dlsets]]
  urls = [
      "https://surviral.at/01_aktuellelagetirol.jpg",
      #"https://www.tirol.gv.at/fileadmin/daten/abwasser/abwasser.json",
  ]
  dir = "covid/abwassermonitoring/tirol"
  sortdir_fmt = "%Y"

  [[dlsets]]
  preset = "wienabwasser"
  urls = [
     "https://stp.wien.gv.at/viennaviz/anonymous/chart/2cbc142d-d1c0-4c43-89f4-54e4d9d5223e/dataSelection?includeBom=0",
  ]
  fname_format = "wienww_cov"

  [[dlsets]]
  preset = "wienabwasser"
  urls = [
     "https://stp.wien.gv.at/viennaviz/anonymous/chart/2a37abdb-544a-445e-bfd6-a2e8ecbaacdf/dataSelection?includeBom=0",
  ]
  fname_format = "wienww_flu"

  [[dlsets]]
  preset = "wienabwasser"
  urls = [
     "https://stp.wien.gv.at/viennaviz/anonymous/chart/3bfafd07-8f89-47a7-877f-22d4ec4ac346/dataSelection?includeBom=0",
  ]
  fname_format = "wienww_rsv"

  [[dlsets]]
  preset = "wienabwasser"
  urls = ["https://go.gv.at/l9ogdabwassermonitoring"]
  use_disposition_fname = false


  [[dlsets]]
  enable = false
  urls = ["https://covid19-dashboard.ages.at/data/data.zip"]
  archive_headers = true
  extract_date = "ages_versiondate"
  dir = ""
  sortdir_fmt = "%Y%m%d"
  fname_format = "ages-dashboard-{}"

  [[dlsets]]
  preset = "abwasser"
  urls = [
    "https://abwassermonitoring.at/cbe1/natmon_01",
    "https://abwassermonitoring.at/cbe1/natmon_02",
    "https://abwassermonitoring.at/cbe1/dl_natmon_01.csv",
    "https://abwassermonitoring.at/cbe1/dl_natmon_variants.csv",
  ]
  sortdir_fmt = "%Y"

  [[dlsets]]
  preset = "abwasser"
  urls = [
    "https://abwassermonitoring.at/cbe1/blverlauf", # TODO: redundant, aber collecthydro unterstützt das csv noch nicht.
    "https://abwassermonitoring.at/cbe1/dl_blverlauf.csv",
  ]
  sortdir_fmt = "%Y/blverlauf"

  [[dlsets]]
  urls = [
    "https://www.ages.at/fileadmin/Corona/Reinfektionen/Reinfektionen.csv",    # Kein Update mehr (kommentarlos)
    "https://www.ages.at/fileadmin/Corona/Epidemiologische-Parameter/R_eff.csv", # Kein Update mehr zu erwarten
    #"https://wissenaktuell.ages.at/fileadmin/AGES2015/Wissen-Aktuell/COVID19/R_eff.csv", # URL geändert, s.u.
    #"https://www.ages.at/fileadmin/AGES2015/Themen/Krankheitserreger_Dateien/Coronavirus/Inzidenz_Impfstatus/Inzidenz_Impfstatus_60plus.csv",
    #"https://www.ages.at/fileadmin/AGES2015/Themen/Krankheitserreger_Dateien/Coronavirus/Inzidenz_Impfstatus/Inzidenz_Impfstatus_Erkrankte_60__Jahre.csv",
  ]
  dir = "covid/ages-ems-extra"

  [[dlsets]]
  urls = [
    "https://www.ages.at/fileadmin/Corona/Wochenbericht/Varianten_Verteilung.csv",
    "https://www.ages.at/fileadmin/Corona/Wochenbericht/Varianten_gesamt_KW.csv",
    "https://www.ages.at/mensch/krankheit/krankheitserreger-von-a-bis-z/coronavirus",
  ]
  dir = "covid/ages-varianten"

  [[dlsets]] # AGES variant CSV does not keep link URL
  tags = ["ages-variant-new"]
  source.kind = "scan_unique_links_re"
  source.urls = [
    "https://www.ages.at/mensch/krankheit/krankheitserreger-von-a-bis-z/coronavirus"
  ]
  source.regex = '"([^"]*Varianten_20\d\d[^"]*\.csv)"'
  dir = "covid/ages-varianten"

  [[dlsets]]
  urls = [
    "https://www.ages.at/fileadmin/Corona/Wochenbericht/timeline-testungen-bundeslaender.csv",
    "https://www.ages.at/fileadmin/Corona/Wochenbericht/timeline-testungen-apotheken-betriebe.csv",
  ]
  dir = "covid/morgenmeldung"
  archive = false


  [[dlsets]]
  urls = [
    "https://viro.meduniwien.ac.at/fileadmin/content/OE/virologie/dokumente/SARS-CoV-2/sars_bundesland_2020.jpg",
    "https://viro.meduniwien.ac.at/fileadmin/content/OE/virologie/dokumente/SARS-CoV-2/sars_woche_2020.jpg"
  ]
  dir = "covid/meduniwien"

  [[dlsets]]
  urls = ["https://raw.githubusercontent.com/cov-lineages/pango-designation/master/pango_designation/alias_key.json"]
  dir = "covid/"
  archive = false

# other

  [[dlsets]]
  urls = [
    "https://www.ages.at/download/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDk0NTkyMDAsImV4cCI6NDA3MDkwODgwMCwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW4vQUdFU18yMDIyLzJfTUVOU0NIL0tyYW5raGVpdC9LcmFua2hlaXRzZXJyZWdlci9NYXNlcm4vTWFzZXJuX1RhYmVsbGVfMjAyNC5jc3YiLCJwYWdlIjoyNTI4fQ.JvQpmMusklkIOhBtLG7UDxs6og9Pcf30_sLV-tTMFLw/Masern_Tabelle_2024.csv",
    "https://www.ages.at/download/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDk0NTkyMDAsImV4cCI6NDA3MDkwODgwMCwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW4vQUdFU18yMDIyLzJfTUVOU0NIL0tyYW5raGVpdC9LcmFua2hlaXRzZXJyZWdlci9NYXNlcm4vTWFzZXJuX1RhYmVsbGVfMjAyMy5jc3YiLCJwYWdlIjoyNTI4fQ.jZA_L6nUjk9HuEYtXzJTgeYIcDENmQlpmrBgJ-xKLiE/Masern_Tabelle_2023.csv",
    "https://www.ages.at/mensch/krankheit/krankheitserreger-von-a-bis-z/pneumokokken",
    "https://www.ages.at/mensch/krankheit/krankheitserreger-von-a-bis-z/grippe",
  ]
  dir = "ages-epi-misc"

  [[dlsets]]
  urls = [
    "https://www.basg.gv.at/fileadmin/uploadVERE/VertriebseinschraenkungenASP.xml",
  ]
  dir = "basg-medicineshortage"

  [[dlsets]]
  enable = false
  urls = [
    "https://medicineshortage.basg.gv.at/vertriebseinschraenkungen/faces/adf.task-flow?_id=main-btf&_document=WEB-INF/main-btf.xml",
  ]
  extract_date = "medshort_updatedate"
  dir = "basg-medicineshortage"

  [[dlsets]]
  tags = ["mtly", "mtly_mort"]
  source.kind = "statat"
  source.urls = [
    "https://data.statistik.gv.at/ogd/json?dataset=OGD_gest_kalwo_alter_GEST_KALWOCHE_5J_100",
    "https://data.statistik.gv.at/ogd/json?dataset=OGD_rate_kalwo_GEST_KALWOCHE_STR_100",
    "https://data.statistik.gv.at/ogd/json?dataset=OGD_gest_kalwo_GEST_KALWOCHE_100",
  ]
  source.exclude_url_regex = 'C-KALWOCHE-0'
  dir = "statat-weekly-deaths"

  [[dlsets]]
  urls = [
    "https://opendata-files.sozialversicherung.at/sari/SARI_Region_Krankenanstalt_v202307.csv?q=now",
    "https://opendata-files.sozialversicherung.at/sari/SARI_Wohnregion_Patient_v202307.csv?q=now",
  ]
  dir = "sari"

  [[dlsets]]
  tags = ["mtly", "mtly_svat"]
  source.kind = "scan_unique_links_re"
  source.urls = [
    # Website > Startseite > Fachinformationen > Zahlen / Daten / Fakten >
    # Statistische Daten aus der SV > Monatsberichte
    "https://www.sozialversicherung.at/cdscontent/?contentid=10007.894919&portal=svportal"
  ]
  source.regex = '<a [^>]*\besvlink_excel\b[^>]*\bhref="([^"]+)"'
  dir = "sozialversicherung-monatsberichte"
  use_disposition_fname = true
  fname_re_sub = ['^Kopie[_ -]von[_ -]', '']
