name: Update covidat-data
on:
  workflow_dispatch:
  schedule:
    - cron: "24 15,5 * * *"
permissions:
  contents: write
defaults:
  run:
    shell: bash
jobs:
  update:
    name: "Update covidat-data and re-generate notebooks on changes"
    concurrency: update-data
    runs-on: ubuntu-latest
    env:
      COVDATA_REPO_ROOT: ${{github.workspace}}/covidat-data
      COVAT_DATA_ROOT: ${{github.workspace}}/covidat-data/data
      COVAT_COLLECT_ROOT: ${{github.workspace}}/tmpdata
      REV_PATH: "export/data-rev.txt"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Setup
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          python -m pip install --upgrade pip
          pip install --upgrade hatch
          hatch -v env create default
      - name: Load old data
        uses: actions/checkout@v3
        with:
          repository: "zeitferne/covidat-data"
          path: ${{ env.COVDATA_REPO_ROOT }}
          token: ${{ secrets.COVAT_DATA_GH_TOKEN }}
          ref: "unreviewed-auto-update"
          fetch-depth: 16 # We run git diff to compare old index later
      - name: Fetch new data
        id: fetch
        env:
          COVAT_BOT_FROM_EMAIL: ${{ secrets.COVAT_BOT_FROM_EMAIL }}
        run: |
          echo "date=`date --rfc-email`" | tee -a "$GITHUB_OUTPUT"
          hatch run dldata --loglevel=debug -c dldata.toml
      - name: Upload new data
        working-directory: ${{ env.COVAT_DATA_ROOT }}
        run: |
          git add -A .
          if ! git diff-index --quiet HEAD; then
              git commit -m "Automatic data update ${{steps.fetch.outputs.date}}"
              git push
          fi
      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          path: notebooks/gh-pages
          ref: gh-pages
          sparse-checkout: export/data-rev.txt
          sparse-checkout-cone-mode: false
      - name: Prepare data update
        id: prepareupdate
        run: |
          LAST_REV=`cat "notebooks/gh-pages/$REV_PATH"`
          echo "Previous revision: $LAST_REV"

          cd "$COVDATA_REPO_ROOT"

          if ! git diff --quiet "$LAST_REV" -- data/basg-medicineshortage data/abwasser; then
            hatch run sh -c 'collectshortage && collecthydro && python -m covidat.collectsvat'
            echo "updated=1" >> "$GITHUB_OUTPUT"
          fi
      - name: Re-generate pages
        if: steps.prepareupdate.outputs.updated
        run: |
          #sudo locale-gen de_AT.UTF-8
          #sudo update-locale

          cd "$COVDATA_REPO_ROOT"
          CUR_REV=`git rev-parse HEAD`
          cd "$GITHUB_WORKSPACE/notebooks/gh-pages"
          git sparse-checkout disable # We don't even want to read, but needed for writing
          hatch -v -e notebooks run sh -c \
            "cd notebooks && python -m covidat.export --execute --notebook monitoring.ipynb"
          echo "$CUR_REV" >"$REV_PATH"
          git add -A
          git commit --amend -m "Automatic notebook update ${{steps.fetch.outputs.date}}"
          git push --force-with-lease




