name: Update covidat-data
on:
    - workflow_dispatch
permissions:
    contents: read
jobs:
    Download-data:
        runs-on: ubuntu-latest
        env:
            COVDATA_REPO_ROOT: covidat-data
            COVAT_DATA_ROOT: covidat-data/data
        steps:
        - uses: actions/checkout@v3
          with:
            persist-credentials: false
        - uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install --upgrade hatch
            hatch env create default
        - name: Load old data
          uses: actions/checkout@v3
          with:
            repository: 'zeitferne/covidat-data'
            path: ${{ env.COVDATA_REPO_ROOT }}
            #token:
        - name: Fetch new data
          run: |
            hatch run dldata -c dldata.toml

